timeout: "1200s"

steps:
  # Step 1: Set up SSH for GitHub and clone repo
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y openssh-client
        mkdir -p ~/.ssh
        gcloud secrets versions access latest --secret=github-ssh-key > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git clone git@github.com:DF-Circles/dl-ai-avatar.git

  # Step 2: Fetch scripts from GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - cp
      - gs://dl-ai-avatar/scripts/script.py
      - gs://dl-ai-avatar/scripts/requirements.txt
      - .

  # Step 3: Install dependencies & run extractor
  - name: 'python:3.9'
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        python script.py

  # Step 4: Upload the result
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - cp
      - docs.txt
      - gs://dl-ai-avatar/documentation.txt

  # Step 5: Logging
  - name: 'bash'
    args:
      - 'echo'
      - 'Build complete'

logsBucket: 'gs://dl-ai-avatar/logs'

options:
  logging: GCS_ONLY
